# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_windows
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_windows)
  glew_config = debug_windows
  glfw3_config = debug_windows
  rp3d_config = debug_windows
  Engone_config = debug_windows
  ProjectUnknown_config = debug_windows

else ifeq ($(config),debug_gcc)
  glew_config = debug_gcc
  glfw3_config = debug_gcc
  rp3d_config = debug_gcc
  Engone_config = debug_gcc
  ProjectUnknown_config = debug_gcc

else ifeq ($(config),release_windows)
  glew_config = release_windows
  glfw3_config = release_windows
  rp3d_config = release_windows
  Engone_config = release_windows
  ProjectUnknown_config = release_windows

else ifeq ($(config),release_gcc)
  glew_config = release_gcc
  glfw3_config = release_gcc
  rp3d_config = release_gcc
  Engone_config = release_gcc
  ProjectUnknown_config = release_gcc

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := glew glfw3 rp3d Engone ProjectUnknown

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

glew:
ifneq (,$(glew_config))
	@echo "==== Building glew ($(glew_config)) ===="
	@${MAKE} --no-print-directory -C glew -f Makefile config=$(glew_config)
endif

glfw3:
ifneq (,$(glfw3_config))
	@echo "==== Building glfw3 ($(glfw3_config)) ===="
	@${MAKE} --no-print-directory -C GLFW3 -f Makefile config=$(glfw3_config)
endif

rp3d:
ifneq (,$(rp3d_config))
	@echo "==== Building rp3d ($(rp3d_config)) ===="
	@${MAKE} --no-print-directory -C rp3d -f Makefile config=$(rp3d_config)
endif

Engone: glew glfw3 rp3d
ifneq (,$(Engone_config))
	@echo "==== Building Engone ($(Engone_config)) ===="
	@${MAKE} --no-print-directory -C Engone -f Makefile config=$(Engone_config)
endif

ProjectUnknown: Engone glew glfw3 rp3d
ifneq (,$(ProjectUnknown_config))
	@echo "==== Building ProjectUnknown ($(ProjectUnknown_config)) ===="
	@${MAKE} --no-print-directory -C ProjectUnknown -f Makefile config=$(ProjectUnknown_config)
endif

clean:
	@${MAKE} --no-print-directory -C glew -f Makefile clean
	@${MAKE} --no-print-directory -C GLFW3 -f Makefile clean
	@${MAKE} --no-print-directory -C rp3d -f Makefile clean
	@${MAKE} --no-print-directory -C Engone -f Makefile clean
	@${MAKE} --no-print-directory -C ProjectUnknown -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_windows"
	@echo "  debug_gcc"
	@echo "  release_windows"
	@echo "  release_gcc"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glew"
	@echo "   glfw3"
	@echo "   rp3d"
	@echo "   Engone"
	@echo "   ProjectUnknown"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"