# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Engone_config = debug
  ProjectUnknown_config = debug

else ifeq ($(config),release)
  Engone_config = release
  ProjectUnknown_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Engone ProjectUnknown

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Engone:
ifneq (,$(Engone_config))
	@echo "==== Building Engone ($(Engone_config)) ===="
	@${MAKE} --no-print-directory -C Engone -f Makefile config=$(Engone_config)
endif

ProjectUnknown:
ifneq (,$(ProjectUnknown_config))
	@echo "==== Building ProjectUnknown ($(ProjectUnknown_config)) ===="
	@${MAKE} --no-print-directory -C ProjectUnknown -f Makefile config=$(ProjectUnknown_config)
endif

clean:
	@${MAKE} --no-print-directory -C Engone -f Makefile clean
	@${MAKE} --no-print-directory -C ProjectUnknown -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Engone"
	@echo "   ProjectUnknown"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"